# -*- mode: ruby -*-
# vi: set ft=ruby :

k8s_cluster = {
  "k8s-worker1" => { :ip => "192.168.11.21", :cpus => 1, :memory => 2048, :ssh => 22001 },
  "k8s-worker2" => { :ip => "192.168.11.22", :cpus => 1, :memory => 2048, :ssh => 22002 },
	"k8s-master" => { :ip => "192.168.11.10", :cpus => 2, :memory => 2500, :ssh => 22000 }
}
NODE_NUMBER = 2
Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/k8s-cluster"]
				if "#{hostname}" == "k8s-master" then
					override.vm.provision "shell", inline: "sudo apt-get update -y"
					override.vm.provision "shell", path: "./config.sh", args: [NODE_NUMBER], privileged: false ## installing python normal user
					override.vm.provision "shell", path: "./jenkins.sh", args: ["k8s-worker1"], privileged: false ## installing jenkins normal user
					override.vm.provision "shell", path: "./monitoring.sh"
				else
          override.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update -y
            sudo timedatectl set-timezone Asia/Seoul   
            sudo echo "nameserver 8.8.8.8 #Google DNS" > /etc/resolv.conf
          SHELL
				end  
      end  
    end  
  end  
end 