# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Node_Number = 1
  ### Worker node ###
  (1..Node_Number).each do |num|
    config.vm.define "k8s-worker#{num}" do |worker|
    worker.vm.box = "bento/ubuntu-24.04"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-worker#{num}"
        vb.cpus = 2
        vb.memory = 2000
        vb.customize ["modifyvm", :id, "--groups", "/k8s-cluster"]
      end
      worker.vm.host_name = "k8s-worker#{num}"
      worker.vm.network "private_network", ip: "192.168.1.2#{num}"
      worker.vm.network "forwarded_port", guest: 22, host: "1004#{num}", auto_correct: true, id: "ssh"
      worker.vm.provision "shell", inline: "sudo apt-get -y update"
    end
  end

  config.vm.define "k8s-master" do |master|
    master.vm.box = "bento/ubuntu-24.04"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master"
      vb.cpus = 2
      vb.memory = 2500
      vb.customize ["modifyvm", :id, "--groups", "/k8s-cluster"]
    end
    master.vm.host_name = "k8s-master"
    master.vm.network "private_network", ip: "192.168.1.10"
    master.vm.network "forwarded_port", guest: 22, host: "10030", auto_correct: true, id: "ssh"
    master.vm.provision "shell", inline: "sudo apt-get -y update"
    master.vm.provision "shell", path: "./config.sh", privileged: false ## installing python with normal user
    master.vm.provision "shell", path: "./jenkins.sh", privileged: false ## installing jenkins with normal user
    master.vm.provision "shell", path: "./monitoring.sh"
  end
end
