- name: 이미 join 됐는지 확인
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: worker join
  command: >
    {{ hostvars[groups['master'][0]].worker_join_command }}
    --node-name {{ inventory_hostname_short }}
  when: not kubelet_conf.stat.exists

- name: worker 레이블
  command: kubectl label node {{ inventory_hostname_short }} role=worker
  delegate_to: "{{ groups['master'][0] }}"
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  ignore_errors: yes
