# -*- mode: ruby -*-
# vi: set ft=ruby :
k8s_cluster ={
  #"k8s-nfs" => { :ip => "192.168.56.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "k8s-worker1" => { :ip => "192.168.60.21", :cpus => 2, :memory => 3000, :ssh => 22001 },
  "k8s-worker2" => { :ip => "192.168.60.22", :cpus => 2, :memory => 3000, :ssh => 22002 },
  "k8s-worker3" => { :ip => "192.168.60.23", :cpus => 2, :memory => 3000, :ssh => 22003 },
  "k8s-master" => { :ip => "192.168.60.10", :cpus => 4, :memory => 3500, :ssh => 22000 }
}
NODE_NUMBER = 3
CLUSTER_NAME = "kubevirt"
DISK_PATH = "C:/VirtualBox VMs/#{CLUSTER_NAME}/disk-"
DISK_NUM = 2

Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.provision "shell", inline: "sudo apt-get update -y"
        override.vm.provision "shell", path: "./config.sh"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/k8s-cluster-ubuntu2204"]
        if "#{hostname}" == "k8s-master" then ## master node
          override.vm.provision "shell", path: "./kubespray.sh", args: [NODE_NUMBER], privileged: false
          override.vm.provision "shell", path: "./metallb.sh", privileged: false
        elsif "#{hostname}" == "k8s-nfs" then ## nfs node
          override.vm.provision "shell", path: "./nfs/nfs.sh", privileged: false
        else ## worker node
          DISK_NUM.times do |i|
            vb.customize ['createhd', '--filename', "#{DISK_PATH}#{hostname}-#{i+1}.vdi", '--size', 1024 * 2] # 2GB
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', i+1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}#{hostname}-#{i+1}.vdi"]
            vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port#{i+1}/Ssd", "1"]
          end
        end
      end  
    end
  end
end