---
- name: kubeadm config 작성
  copy:
    dest: /tmp/kubeadm-config.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      networking:
        podSubnet: {{ pod_cidr }}
      ---
      apiVersion: kubeproxy.config.k8s.io/v1alpha1
      kind: KubeProxyConfiguration
      mode: "nftables"

- name: kubeadm init
  command: kubeadm init --node-name master-1 --config /tmp/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf
