- name: .kube 디렉토리 생성
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu

- name: admin.conf 복사
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: kubeconfig 로컬 저장
  fetch:
    src: /home/ubuntu/.kube/config
    dest: ~/.kube/config-k8s-storage-lab
    flat: yes
