version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
    #Root 계정 비번
      - MYSQL_ROOT_PASSWORD=1234
    #사용자 정보
      - MYSQL_USER=user
      - MYSQL_PASSWORD=4321
    #DB명
      - MYSQL_DATABASE=wordpressdb
    volumes:
      - mysqldb:/var/lib/mysql
    #기입해야만 localhost의 포트로 지정
    ports:
      - 3306:3306
    networks:
      - bridge
  wordpress:
    image: wordpress
    environment:
      #네트워크 정보
      - WORDPRESS_HOST=host.docker.internal
      #일반 유저 정보
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=4321
      #database 명
      - WORDPRESS_DB_NAME=wordpressdb
    volumes:
      - wordpress:/var/www/html
    networks:
      - bridge
    #기입해야만 localhost의 포트로 지정
    ports:
      - 80:80
    depends_on:
      - mysql
volumes:
  mysqldb:
  wordpress:
networks:
  bridge:
