version: "3"
services:
  wp-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpadm
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - wp-db-vol:/var/lib/mysql
    networks:
      - wp-net
  wp-web:
    depends_on:
      - wp-db
    image: wordpress:5-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: wpadm
      WORDPRESS_DB_PASSWORD: P@ssw0rd
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "80:80"
    volumes:
      - wp-web-vol:/var/www/html
    networks:
      - wp-net
volumes:
  wp-db-vol:
  wp-web-vol:
networks:
  wp-net:
