# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "minikube-master" do |node|
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.box_version = "202309.08.0"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "minikube-master"
      vb.memory = 16000
      vb.cpus = 4
    end
    node.vm.hostname = "minikube-master"
    node.vm.network "private_network", ip: "192.168.80.10"
    node.vm.network "forwarded_port", guest: 22, host: 22222, auto_correct: true, id: "ssh"
    node.vm.provision "shell", inline: "sudo apt-get update -y"
    node.vm.provision "shell", path: "./minikube.sh", privileged: false
    #node.vm.provision "shell", path: "./kubevirt.sh", privileged: false
  end
end
