- name: 커널 모듈 등록 (modules-load.d)
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
      nf_tables
      nft_masq

- name: 커널 모듈 즉시 로드
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
    - nf_tables
    - nft_masq
