- name: cloud-init 완료 대기
  command: cloud-init status --wait
  changed_when: false
  failed_when: false

- name: unattended-upgrades 비활성화
  systemd:
    name: unattended-upgrades
    state: stopped
    enabled: no
  failed_when: false

- name: 공통 패키지 설치
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - nfs-common
      - open-iscsi
      - python3
      - conntrack
      - socat
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive