# -*- mode: ruby -*-
# vi: set ft=ruby :
k8s_cluster ={
  #"k8s-nfs" => { :ip => "172.16.10.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "k8s-master" => { :ip => "172.16.10.10", :cpus => 4, :memory => 4000, :ssh => 22000 },
  "k8s-worker1" => { :ip => "172.16.10.21", :cpus => 2, :memory => 3500, :ssh => 22001 },
  "k8s-worker2" => { :ip => "172.16.10.22", :cpus => 2, :memory => 3500, :ssh => 22002 }
  #"k8s-worker3" => { :ip => "172.16.10.23", :cpus => 2, :memory => 3500, :ssh => 22003 }
}
NODE_NUMBER = 2
CLUSTER_NAME = "k8s-ubuntu2204-kubeadm"

Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        config.vm.box_version = "202309.08.0"
        override.vm.provision "shell", inline: "sudo apt-get update -y"
        override.vm.provision "shell", path: "./config.sh", privileged: false
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/#{CLUSTER_NAME}"]
        if "#{hostname}" == "k8s-master" then ## master node
          override.vm.provision "shell", path: "./kubeadm_master.sh", privileged: false
          override.vm.provision "shell", path: "./kubevirt/kubevirt.sh", privileged: false
        else
          override.vm.provision "shell", path: "./kubeadm_worker.sh", privileged: false
        end
      end  
    end
  end
end