# -*- mode: ruby -*-
# vi: set ft=ruby :

# 클러스터 설정
CLUSTER_NAME = "k8s-ubuntu2204-kubeadm"

# 노드 설정
K8S_CLUSTER ={
  #"k8s-nfs" => { :ip => "172.16.10.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "k8s-master" => { :ip => "172.16.10.10", :cpus => 4, :memory => 4000, :ssh => 22000 },
  "k8s-worker1" => { :ip => "172.16.10.21", :cpus => 2, :memory => 3500, :ssh => 22001 },
  "k8s-worker2" => { :ip => "172.16.10.22", :cpus => 2, :memory => 3500, :ssh => 22002 }
  #"k8s-worker3" => { :ip => "172.16.10.23", :cpus => 2, :memory => 3500, :ssh => 22003 }
}

Vagrant.configure("2") do |config|
  # 공통 설정
  config.vm.box = "bento/ubuntu-22.04"

  K8S_CLUSTER.each do |hostname, node|
    config.vm.define hostname do |machine|
      # 네트워크 및 기본 설정
      machine.vm.hostname = hostname  # 호스트명 설정 수정
      machine.vm.network "private_network", ip: node[:ip]
      machine.vm.network "forwarded_port", guest: 22, host: node[:ssh], auto_correct: true, id: "ssh"  # :ssh_port -> :ssh로 수정
      machine.vm.provision "shell", inline: "sudo apt-get update -y"

      # VirtualBox 제공자 설정
      machine.vm.provider "virtualbox" do |vb|
        vb.name = hostname
        vb.memory = node[:memory]
        vb.cpus = node[:cpus]
        vb.customize ["modifyvm", :id, "--groups", "/#{CLUSTER_NAME}"]
      end

      # 공통 스크립트 실행
      machine.vm.provision "shell", path: "scripts/common.sh", privileged: false

      # 노드별 스크립트 실행 (hostname 기준으로 조건 확인)
      if hostname == "k8s-master"
        machine.vm.provision "shell", path: "scripts/master.sh", privileged: false
        machine.vm.provision "shell", path: "scripts/kubevirt.sh", privileged: false
      else
        machine.vm.provision "shell", path: "scripts/worker.sh", privileged: false
      end
    end
  end
end