version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mydb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wordpressdb
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb:
    driver: local
