# -*- mode: ruby -*-
# vi: set ft=ruby :

## prepare for libvirt in windows 11
#MSYS2
#pacman -S mingw-w64-x86_64-qemu mingw-w64-x86_64-libvirt base-devel
#https://rubyinstaller.org/downloads/
#vagrant plugin install vagrant-libvirt
Vagrant.configure("2") do |config|
  GUEST_IP = "10.64.140.43" ## manually port-forwarding
  ## libvirt provider for gpu passthrough
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202309.08.0"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 14000
    libvirt.cpus = 8
    libvirt.disk_bus = "virtio"
  end
  config.vm.hostname = "microk8s-master"
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.network "forwarded_port", guest: 22, host: 10030, auto_correct: true, id: "ssh"
  config.vm.network "forwarded_port", guest: 80, host: 1234, guest_ip: GUEST_IP, id: "dashboard"
  config.vm.provision "shell", inline: "sudo apt-get update -y"
  #config.vm.provision "shell", path: "./microk8s.sh", privileged: false
  #config.vm.provision "shell", path: "./juju.sh", privileged: false
end
