# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "microk8s-master" do |node|
    GUEST_IP = "10.64.140.43" ## manually port-forwarding
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.provider "virtualbox" do |vb|
      vb.name = "microk8s-master"
      vb.memory = 10000
      vb.cpus = 4
    end
    node.vm.hostname = "microk8s-master"
    node.vm.network "private_network", ip: "192.168.10.10"
    node.vm.network "forwarded_port", guest: 22, host: 10030, auto_correct: true, id: "ssh"
    node.vm.network "forwarded_port", guest: 80, host: 1234, guest_ip: GUEST_IP, id: "dashboard"
    node.vm.provision "shell", inline: "sudo apt-get update -y"
    ## no gpu passthrough
    node.vm.provision "shell", path: "./no_gpu/microk8s.sh", privileged: false
    node.vm.provision "shell", path: "./no_gpu/juju.sh", privileged: false
  end
end
