# -*- mode: ruby -*-
# vi: set ft=ruby :
ceph_cluster ={
  #"ceph-nfs" => { :internal_ip => "10.0.1.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "ceph2" => { :internal_ip => "10.0.1.22", :cpus => 4, :memory => 4000, :ssh => 22202 },
  "ceph3" => { :internal_ip => "10.0.1.23", :cpus => 4, :memory => 4000, :ssh => 22203 },
  "ceph1" => { :internal_ip => "10.0.1.21", :cpus => 4, :memory => 4000, :ssh => 22201 }
}
CLUSTER_NAME = "k8s-cluster-ubuntu2204"
DISK_PATH = "C:/VirtualBox VMs/#{CLUSTER_NAME}/disk-"
OSD_NUM = 3

Vagrant.configure("2") do |config|
  ceph_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.provision "shell", inline: "sudo apt-get update -y"
        override.vm.network "private_network", ip: "#{info[:internal_ip]}", virtualbox__intnet: "ceph_internal"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/#{CLUSTER_NAME}"]
        OSD_NUM.times do |i|
          vb.customize ['createhd', '--filename', "#{DISK_PATH}#{hostname}-#{i+1}.vdi", '--size', 1024 * 5] # 5GB
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', i+1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}#{hostname}-#{i+1}.vdi"]
          vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port#{i+1}/Ssd", "1"]
        end
        if "#{hostname}" == "ceph1" then
          override.vm.provision "shell", path: "./ceph-bootstrap.sh", privileged: false
        else
          override.vm.provision "shell", path: "./ceph-node.sh", privileged: false
        end
      end  
    end
  end
end