# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "terraform-master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "terraform-master"
      vb.cpus = 4
      vb.memory = 8000
    end
    master.vm.network "private_network", ip: "192.168.10.10"
    master.vm.network "forwarded_port", guest: 22, host: "10030", auto_correct: true, id: "ssh"
    master.vm.provision "shell", inline: "sudo apt-get update -y"
    #master.vm.provision "shell", path: "./kubeflow.sh"
  end
end
