# -*- mode: ruby -*-
# vi: set ft=ruby :

# 노드 설정
K8S_CLUSTER = {
  #"k8s-nfs" => { :ip => "192.168.56.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "k8s-worker1" => { :ip => "192.168.56.21", :cpus => 2, :memory => 3000, :ssh => 22001 },
  "k8s-worker2" => { :ip => "192.168.56.22", :cpus => 2, :memory => 3000, :ssh => 22002 },
  "k8s-worker3" => { :ip => "192.168.56.23", :cpus => 2, :memory => 3000, :ssh => 22003 },
  "k8s-master" => { :ip => "192.168.56.10", :cpus => 4, :memory => 4000, :ssh => 22000, :provision => ["./kubespray.sh", "./jenkins.sh", "./monitoring.sh", "./ceph-rook.sh"] }
}

# 환경 설정
CLUSTER_NAME = "k8s-ubuntu2204-kubespray"
NODE_NUMBER = K8S_CLUSTER.size()

Vagrant.configure("2") do |config|
  K8S_CLUSTER.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.box = "bento/ubuntu-22.04"
      cfg.vm.host_name = hostname
      
      # 네트워크 설정
      cfg.vm.network "private_network", ip: info[:ip]
      cfg.vm.network "forwarded_port", guest: 22, host: info[:ssh], auto_correct: true, id: "ssh"
      
      # VirtualBox 설정
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = hostname
        vb.gui = false
        vb.memory = info[:memory]
        vb.cpus = info[:cpus]
        vb.customize ["modifyvm", :id, "--groups", "/#{CLUSTER_NAME}"]
      end
      
      # 프로비저닝 스크립트 실행
      if info[:provision]
        info[:provision].each do |script|
          cfg.vm.provision "shell", path: script, args: [NODE_NUMBER], privileged: false
        end
      end
    end
  end
end