# -*- mode: ruby -*-
# vi: set ft=ruby :

k8s_cluster = {
  "k8s-nfs" => { :ip => "192.168.56.100", :cpus => 1, :memory => 800, :ssh => 22200 },
  "k8s-worker1" => { :ip => "192.168.56.21", :cpus => 1, :memory => 1800, :ssh => 22001 },
  "k8s-worker2" => { :ip => "192.168.56.22", :cpus => 1, :memory => 1800, :ssh => 22002 },
	"k8s-master" => { :ip => "192.168.56.10", :cpus => 2, :memory => 2500, :ssh => 22000 }
}
NODE_NUMBER = 2
Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/k8s-cluster"]
				if "#{hostname}" == "k8s-master" then
					override.vm.provision "shell", inline: "sudo apt-get update -y"
					override.vm.provision "shell", path: "./master/master.sh"
          override.vm.provision "shell", path: "./master/kubespray.sh", args: [NODE_NUMBER], privileged: false ## installing python normal user
					override.vm.provision "shell", path: "./master/jenkins.sh", args: ["k8s-worker1"], privileged: false ## installing jenkins normal user
					override.vm.provision "shell", path: "./master/monitoring.sh"
        elsif "#{hostname}" == "k8s-nfs" then
          override.vm.provision "shell", path: "./nfs/nfs.sh"
				else
          override.vm.provision "shell", path: "./worker/worker.sh"
				end  
      end  
    end  
  end  
end 