- name: K8s keyrings 디렉토리
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: K8s GPG 키 등록
  shell: |
    curl -fsSL \
      https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key \
    | gpg --dearmor \
      -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: K8s apt 저장소 추가
  apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /
    state: present
    filename: kubernetes

- name: kubeadm kubelet kubectl 설치
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: present
    update_cache: yes

- name: 버전 고정
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [kubelet, kubeadm, kubectl]

- name: kubelet 활성화
  systemd:
    name: kubelet
    enabled: yes
