# -*- mode: ruby -*-
# vi: set ft=ruby :

# password.rb 파일 로드
require_relative 'password'

# 버전 관리 변수
VERSION_CONFIG = {
  :ubuntu_box => "bento/ubuntu-22.04",
  :kubernetes => "v1.31.0",
  :calico => "v3.27.0",
  :ceph => "quincy",
  :ceph_csi => "3.9.0"
}

# 네트워크 설정
NETWORK_CONFIG = { :pod_cidr => "10.244.0.0/16", :master_ip => "192.168.57.10", :network_prefix => "192.168.57" }

# K8S 클러스터 설정
CLUSTER_NAME = "ubuntu-ceph-1"
K8S_CLUSTER = {
  "k8s-worker-1" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.11", :cpus => 3, :memory => 2000, :ssh_port => 22001 },
  "k8s-worker-2" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.12", :cpus => 3, :memory => 2000, :ssh_port => 22002 },
  "k8s-worker-3" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.13", :cpus => 3, :memory => 2000, :ssh_port => 22003 },
  "k8s-master" => { :ip => "#{NETWORK_CONFIG[:master_ip]}", :cpus => 4, :memory => 3500, :ssh_port => 22000 }
}
K8S_WORKER_NODES = K8S_CLUSTER.length - 1

# Ceph OSD 설정
CEPH_OSD = { :count => 2, :disk_size => 1024*8 }
OSD_DISK_BASE_PATH = "C:/VirtualBox VMs/#{CLUSTER_NAME}"

Vagrant.configure("2") do |config|  
  K8S_CLUSTER.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.box = VERSION_CONFIG[:ubuntu_box]
      cfg.vm.host_name = hostname      
      cfg.vm.network "private_network", ip: info[:ip]
      cfg.vm.network "forwarded_port", guest: 22, host: info[:ssh_port], id: "ssh", auto_correct: true 
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = hostname
        vb.memory = info[:memory]
        vb.cpus = info[:cpus]
        vb.customize ["modifyvm", :id, "--groups", "/#{CLUSTER_NAME}"]
        
        # 워커 노드일 경우 OSD 디스크 추가
        if hostname.include? "worker"
          CEPH_OSD[:count].times do |i|
            osd_disk = "#{OSD_DISK_BASE_PATH}/#{hostname}-osd-#{i}.vdi"
            vb.customize ['createhd', '--filename', osd_disk, '--size', CEPH_OSD[:disk_size], '--variant', 'Fixed']          
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1 + i, '--device', 0, '--type', 'hdd', '--medium', osd_disk]                
            vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port#{1+i}/NonRotational", "1"] # SSD 설정 추가
          end
        end
      end
      
      # 노드 공통 설정
      cfg.vm.provision "shell", path: "../kubeadm-setup.sh", 
        args: ["#{NETWORK_CONFIG[:master_ip]}", "#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}", "#{VERSION_CONFIG[:kubernetes]}"]
      
      # 마스터 노드 설정
      if hostname == "k8s-master"
        cfg.vm.provision "shell", path: "../kubeadm-master.sh", 
          args: ["#{NETWORK_CONFIG[:master_ip]}", "#{NETWORK_CONFIG[:pod_cidr]}", "#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}", "#{VERSION_CONFIG[:kubernetes]}", "#{VERSION_CONFIG[:calico]}"]
        # Ceph 설치 및 설정 (OSD 준비 통합)
        cfg.vm.provision "shell", path: "./scripts/cephadm-setup.sh", name: "cephadm", 
          args: ["#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}", "#{VAGRANT_PASSWORD}", "#{VERSION_CONFIG[:ceph]}"], 
          privileged: true
        # Filesystem Storage 설치
        cfg.vm.provision "shell", path: "./scripts/cephadm-cephfs.sh", name: "cephfs", 
          args: ["#{NETWORK_CONFIG[:network_prefix]}", "#{NETWORK_CONFIG[:master_ip]}", "#{VERSION_CONFIG[:ceph_csi]}"], 
          privileged: true
        # block Storage 설치  
        cfg.vm.provision "shell", path: "./scripts/cephadm-rbd.sh", name: "cephrbd", 
          args: ["#{NETWORK_CONFIG[:network_prefix]}", "#{NETWORK_CONFIG[:master_ip]}", "#{VERSION_CONFIG[:ceph_csi]}"], 
          privileged: true
        # Object Storage 설치 (옵션 3 (s3cmd, openstack 모두) 선택)
        cfg.vm.provision "shell", path: "./scripts/cephadm-object-storage.sh", name: "cephobject", 
          args: ["#{NETWORK_CONFIG[:network_prefix]}", "#{NETWORK_CONFIG[:master_ip]}"], 
          env: {"S3_CLIENT_CHOICE" => "3"},
          privileged: true
      end
    end
  end
end