# -*- mode: ruby -*-
# vi: set ft=ruby :

# password.rb 파일 로드
require_relative 'password'

# 네트워크 및 K8s 설정
NETWORK_CONFIG = { 
  :pod_cidr => "10.244.0.0/16", 
  :master_ip => "192.168.56.10", 
  :network_prefix => "192.168.56" 
}
# Ceph OSD 공통 설정
CEPH_OSD = { :count => 2, :disk_size => 1024*8 }
# 노드 설정 - 워커 노드를 먼저, 마스터 노드를 마지막에 정의
K8S_CLUSTER = {
  "k8s-worker-1" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.11", :cpus => 2, :memory => 2000, :ssh_port => 22001 },
  "k8s-worker-2" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.12", :cpus => 2, :memory => 2000, :ssh_port => 22002 },
  "k8s-worker-3" => { :ip => "#{NETWORK_CONFIG[:network_prefix]}.13", :cpus => 2, :memory => 2000, :ssh_port => 22003 },
  "k8s-master" => { :ip => "#{NETWORK_CONFIG[:master_ip]}", :cpus => 4, :memory => 3500, :ssh_port => 22000 }
}
# K8S_CLUSTER 해시에서 워커 노드 수를 동적으로 계산
K8S_WORKER_NODES = K8S_CLUSTER.length - 1
# OSD 디스크 기본 경로 설정
OSD_DISK_BASE_PATH = "C:/VirtualBox VMs/ubuntu-ceph"

Vagrant.configure("2") do |config|  
  # 각 노드 구성 (워커 노드가 먼저, 마스터 노드가 마지막에 프로비저닝됨)
  K8S_CLUSTER.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.box = "bento/ubuntu-22.04"
      cfg.vm.host_name = hostname      
      cfg.vm.network "private_network", ip: info[:ip]
      cfg.vm.network "forwarded_port", guest: 22, host: info[:ssh_port], id: "ssh", auto_correct: true 

      cfg.vm.provider "virtualbox" do |vb|
        vb.name = hostname
        vb.memory = info[:memory]
        vb.cpus = info[:cpus]
        vb.customize ["modifyvm", :id, "--groups", "/ubuntu-ceph"]
        
        # 워커 노드일 경우 OSD 디스크 추가
        if hostname.include? "worker"
          CEPH_OSD[:count].times do |i|
            osd_disk = "#{OSD_DISK_BASE_PATH}/#{hostname}-osd-#{i}.vdi"
            vb.customize ['createhd', '--filename', osd_disk, '--size', CEPH_OSD[:disk_size], '--variant', 'Fixed']          
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1 + i, '--device', 0, '--type', 'hdd', '--medium', osd_disk]    
            # SSD 설정 추가
            vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port#{1+i}/NonRotational", "1"]
          end
        end
      end
      
      # 노드 공통 설정
      cfg.vm.provision "shell", path: "../provision/kubeadm-common.sh", 
        args: ["#{NETWORK_CONFIG[:master_ip]}", "#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}"]
      
      # 마스터 노드 설정
      if hostname == "k8s-master"
        cfg.vm.provision "shell", path: "../provision/kubeadm-master.sh", 
          args: ["#{NETWORK_CONFIG[:master_ip]}", "#{NETWORK_CONFIG[:pod_cidr]}", "#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}"]
        # Ceph 설치 및 설정 (OSD 준비 통합)
        cfg.vm.provision "shell", path: "./scripts/cephadm-setup.sh", name: "cephadm", 
          args: ["#{CEPH_OSD[:count]}", "#{NETWORK_CONFIG[:network_prefix]}", "#{K8S_WORKER_NODES}", "#{VAGRANT_PASSWORD}"], 
          privileged: true
        # Filesystem Storage 설치
        cfg.vm.provision "shell", path: "./scripts/cephadm-cephfs.sh", name: "cephfs", privileged: true
        # block Storage 설치
        cfg.vm.provision "shell", path: "./scripts/cephadm-rbd.sh", name: "cephrbd", privileged: true
        # Object Storage 설치 (옵션 3 (s3cmd, awscli 모두) 선택)
        cfg.vm.provision "shell", path: "./scripts/cephadm-object-storage.sh", 
          name: "cephobject", 
          env: {"S3_CLIENT_CHOICE" => "3"},
          privileged: true
      end
    end
  end
end