Vagrant.configure("2") do |config|
  NODE_NUMBER = 3
  DISK_PATH = "D:/VirtualBoxVMs/k8s-cluster-centos7/disk-"
#  ### NFS Server ###  
#  config.vm.define "k8s-NFS" do |nfs|
#    nfs.vm.box = "centos/7"
#    nfs.vm.provider "virtualbox" do |vb|
#      vb.name = "k8s-nfs-centos7"
#      vb.cpus = 1
#      vb.memory = 800
#      vb.customize ["modifyvm", :id, "--groups", "/k8s-cluster-centos7"]
#    end
#    nfs.vm.host_name = "k8s-nfs-centos7"
#    nfs.vm.network "private_network", ip: "192.168.1.100"
#    nfs.vm.network "forwarded_port", guest: 22, host: "10100", auto_correct: true, id: "ssh"
#    nfs.vm.provision "shell", inline: "sudo yum -y update"
#    nfs.vm.provision "shell", path: "./common/config.sh"
#    nfs.vm.provision "shell", path: "./nfs/nfs_node.sh"
#  end
  ### Worker node ###
  (1..NODE_NUMBER).each do |num|
    config.vm.define "k8s-worker#{num}-centos7" do |worker|      
      worker.vm.box = "centos/7"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-worker#{num}-centos7"
        vb.cpus = 1
        vb.memory = 2300
        vb.customize ["modifyvm", :id, "--groups", "/k8s-cluster-centos7"]
        vb.customize ['createhd', '--filename', "#{DISK_PATH}k8s-worker#{num}.vdi", '--size', 1024 * 10] # 10GB
        vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}k8s-worker#{num}.vdi"]
        vb.customize ['setextradata', :id, 'VBoxInternal/Devices/ahci/0/Config/Port1/SSD', 1]
      end
      worker.vm.host_name = "k8s-worker#{num}"
      worker.vm.network "private_network", ip: "192.168.1.2#{num}"
      worker.vm.network "forwarded_port", guest: 22, host: "1004#{num}", auto_correct: true, id: "ssh"
      worker.vm.provision "shell", inline: "sudo yum -y update"   
      worker.vm.provision "shell", path: "./common/config.sh"   
    end
  end

  ### Master Node ####
  config.vm.define "k8s-master-centos7" do |master|
    master.vm.box = "centos/7"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master-centos7"
      vb.cpus = 3
      vb.memory = 2500
      vb.customize ["modifyvm", :id, "--groups", "/k8s-cluster-centos7"]
    end
    master.vm.host_name = "k8s-master"
    master.vm.network "private_network", ip: "192.168.1.10"
    master.vm.network "forwarded_port", guest: 22, host: "10030", auto_correct: true, id: "ssh"
    master.vm.provision "shell", inline: "sudo yum -y update"
    master.vm.provision "shell", path: "./common/config.sh"
    master.vm.provision "shell", path: "./master_node/kubespray.sh", args: [NODE_NUMBER], privileged: false ## install pip, ansible by normal user
    master.vm.provision "shell", path: "./master_node/ceph.sh", privileged: false
    master.vm.provision "shell", path: "./master_node/monitoring.sh"
    #master.vm.provision "shell", path: "./master_node/jenkins.sh"
  end
end