# -*- mode: ruby -*-
# vi: set ft=ruby :
k8s_cluster ={
  "nfs" => { :ip => "192.168.55.100", :cpus => 2, :memory => 1000, :ssh => 22200 },
  "worker1" => { :ip => "192.168.55.21", :cpus => 6, :memory => 14000, :ssh => 22001 },
  "master" => { :ip => "192.168.55.10", :cpus => 6, :memory => 16000, :ssh => 22000 }
}

DISK_PATH = "D:/VirtualBoxVMs/kubeflow-ubuntu2204/disk-"
Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.provision "shell", inline: "sudo apt-get update -y"
        override.vm.provision "shell", path: "./common/config.sh"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/kubeflow"]
				if "#{hostname}" == "master" then
          vb.customize ['createhd', '--filename', "#{DISK_PATH}#{hostname}.vdi", '--size', 1024 * 80] # 80GB
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}#{hostname}.vdi"]
          vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port1/NonRotational", "1"]
          override.vm.provision "shell", path: "./master/kubespray.sh", privileged: false
          override.vm.provision "shell", path: "./kubeflow.sh"
        elsif "#{hostname}" == "nfs" then
          # vagrant plugin install vagrant-disksize
          override.disksize.size = '50GB'
          override.vm.provision "shell", path: "./nfs/nfs.sh"
        else
          override.vm.provision "shell", inline: "sudo apt-get install nfs-common -y"
          vb.customize ['createhd', '--filename', "#{DISK_PATH}#{hostname}.vdi", '--size', 1024 * 80] # 80GB
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}#{hostname}.vdi"]
          vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port1/NonRotational", "1"]
        end
      end  
    end
  end
end