apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:12.4
    resources:
      limits:
        nvidia.com/gpu: 1
    command: ["nvidia-smi"]
