apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-pipeline-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: first-step
        template: echo
  - name: echo
    container:
      image: python:3.7
      command: ["python", "-c"]
      args: ["print('Hello, Kubeflow!')"]