# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Worker_Nodes = 2
k8s_cluster = {
  "w1.example.com" => { :ip => "192.168.14.51", :cpus => 1, :memory => 2048 },
	"m.example.com" => { :ip => "192.168.14.50", :cpus => 2, :memory => 2048 },
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  (1..Worker_Nodes).each do |worker|
    config.vm.define "worker#{worker}" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.host_name = "worker#{worker}"
      cfg.vm.network "private_network", ip: "192.168.55.1#{worker}"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "worker#{worker}"
        vb.cpus = 1
        vb.memory = 1024
        vb.gui = false
      end
      cfg.vm.provision "shell", path: "ssh_config.sh", privileged: true
      cfg.vm.provision "shell", path: "k8s_common_install.sh", privileged: true
      cfg.vm.provision "shell", path: "k8s_enroll_DNS.sh", args: Worker_Nodes, privileged: true
    end
  end
  config.vm.define "master" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "master"
    cfg.vm.network "private_network", ip: "192.168.55.10"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.cpus = 2
      vb.memory = 2048
      vb.gui = false
    end
    cfg.vm.provision "shell", path: "ssh_config.sh", privileged: true
    cfg.vm.provision "shell", path: "k8s_common_install.sh", privileged: true
    cfg.vm.provision "shell", path: "k8s_enroll_DNS.sh", args: Worker_Nodes, privileged: true
    cfg.vm.provision "shell", path: "k8s_master.sh", privileged: true
    cfg.vm.provision "shell", path: "send_k8s_token.sh", args: Worker_Nodes, privileged: false
  end
end
