# -*- mode: ruby -*-
# vi: set ft=ruby :
N = 1
Vagrant.configure("2") do |config|
  (1..N).each do |worker|
    config.vm.define "worker#{worker}" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "worker#{worker}"
        vb.cpus = 1
        vb.memory = 1536
        vb.gui = false
      end
      cfg.vm.host_name = "worker#{worker}"
      cfg.vm.network "private_network", ip: "192.168.55.1#{N}"
      cfg.vm.provision "shell", path: "ssh_config.sh", privileged: true
      cfg.vm.provision "shell", path: "k8s_common_install.sh", privileged: true
    end
  end
  config.vm.define "master" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.cpus = 2
      vb.memory = 2048
      vb.gui = false
    end
    cfg.vm.host_name = "master"
    cfg.vm.network "private_network", ip: "192.168.55.10"
    cfg.vm.provision "shell", path: "ssh_config.sh", privileged: true
    cfg.vm.provision "shell", path: "k8s_common_install.sh", privileged: true
    cfg.vm.provision "shell", path: "k8s_master.sh", privileged: true
    #cfg.vm.provision "shell", path: "send_k8s_token.sh", privileged: false
  end
end
