# -*- mode: ruby -*-
# vi: set ft=ruby :
k8s_cluster ={
  #"k8s-nfs" => { :ip => "192.168.56.100", :cpus => 2, :memory => 800, :ssh => 22200 },
  "k8s-worker1" => { :ip => "192.168.56.21", :cpus => 2, :memory => 2000, :ssh => 22001 },
  "k8s-worker2" => { :ip => "192.168.56.22", :cpus => 2, :memory => 2000, :ssh => 22002 },
  "k8s-worker3" => { :ip => "192.168.56.23", :cpus => 2, :memory => 2000, :ssh => 22003 },
  "k8s-master" => { :ip => "192.168.56.10", :cpus => 3, :memory => 3000, :ssh => 22000 }
}
NODE_NUMBER = 3
DISK_PATH = "D:/VirtualBoxVMs/k8s-cluster-ubuntu2204/disk-"
Vagrant.configure("2") do |config|
  k8s_cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider "virtualbox" do |vb,override|
        config.vm.box = "bento/ubuntu-22.04"
        override.vm.provision "shell", inline: "sudo apt-get update -y"
        override.vm.provision "shell", path: "./common/config.sh"
        override.vm.network "private_network", ip: "#{info[:ip]}"
        override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh]}", auto_correct: true, id: "ssh"
        override.vm.host_name = hostname
        vb.name = hostname
				vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", info[:memory], "--cpus", info[:cpus], "--groups", "/k8s-cluster-ubuntu2204"]
        if "#{hostname}" != "k8s-master" && "#{hostname}" != "k8s-nfs" then
          vb.customize ['createhd', '--filename', "#{DISK_PATH}#{hostname}.vdi", '--size', 1024 * 10] # 10GB
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "#{DISK_PATH}#{hostname}.vdi"]
          vb.customize ['setextradata', :id, "VBoxInternal/Devices/ahci/0/Config/Port1/NonRotational", "1"]
        end 
				if "#{hostname}" == "k8s-master" then
          override.vm.provision "shell", path: "./master/kubespray.sh", args: [NODE_NUMBER], privileged: false
					#override.vm.provision "shell", path: "./master/jenkins.sh", args: ["k8s-worker1"], privileged: false ## installing jenkins normal user
					#override.vm.provision "shell", path: "./master/monitoring.sh"
          override.vm.provision "shell", path: "./master/ceph.sh", privileged: false
        elsif "#{hostname}" == "k8s-nfs" then
          # vagrant plugin install vagrant-disksize
          override.disksize.size = '50GB'
          override.vm.provision "shell", path: "./nfs/nfs.sh"
        end
      end  
    end
  end
end