---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-gpfs
spec:
  accessModes: [ReadWriteMany]
  storageClassName: gpfs-scale
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-gpfs
spec:
  containers:
  - name: test
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        echo 'gpfs OK' > /data/test.txt && cat /data/test.txt
        echo "--- 마운트 정보 ---"
        df -hT /data
        echo "--- 파일시스템 타입 ---"
        stat -f /data
        sleep 60
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test-pvc-gpfs
  restartPolicy: Never
