---
- name: Helm 설치 여부 확인
  command: which helm
  register: helm_check
  failed_when: false
  changed_when: false

- name: Helm 설치
  shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: helm_check.rc != 0

- name: Helm 버전 확인
  command: helm version --short
  register: helm_version
  changed_when: false

- name: Helm 버전 출력
  debug:
    msg: "Helm: {{ helm_version.stdout }}"
